#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'coreEnv', 'yajlFlags', 'licensesFlags' )

coreEnv.MergeFlags( yajlFlags )
coreEnv.MergeFlags( licensesFlags )
coreEnv.Prepend( LIBS = coreEnv.StaticLibrary( 'DG', Glob('*.cpp') ) )
