#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'fabricExtsDistDir' )

mathPluginEnv = extsEnv.Clone()
mathPlugin = mathPluginEnv.SharedLibrary( 'FabricMath', Glob('*.cpp') ),
mathManifest = mathPluginEnv.File('FabricMath.fpm.json'),
mathKL = mathPluginEnv.File('FabricMath.kl'),
mathFiles = [mathManifest, mathPlugin, mathKL]

Return( 'mathFiles' )
