#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

import os
Import( 'env', 'installerName', 'archDistDir', 'installerRootDistDir', 'buildArch', 'FABRIC_VERSION' )

pkgID = "com.fabric-engine.FabricNPAPIPlugin." + buildArch
pkgBuilder = Builder(
  action = "mkdir -p $TARGET && /Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker --root $SOURCE --out $TARGET --id " + pkgID + " --version " + FABRIC_VERSION + " --title '" + installerName + "'"
)
dmgBuilder = Builder(
  action = "hdiutil create $TARGET -volname '" + installerName + "' -fs HFS+ -srcfolder $SOURCE"
)
env.Append( BUILDERS = { 'Pkg': pkgBuilder, 'Dmg': dmgBuilder } )

installerDistDir = archDistDir.Dir( 'installer' )
pkgDir = installerDistDir.Dir( installerName + ".pkg" )
installerPkg = env.Pkg(
  target = pkgDir,
  source = installerRootDistDir,
)
installerDmgFile = archDistDir.Dir( installerName + ".dmg" )
installerDmg = env.Dmg(
  target = installerDmgFile,
  source = installerDistDir,
)

Alias( 'installer', installerDmg )
