#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'fabricExtsDistDir', 'opencvFlags', 'ExtSLName', 'buildOS', 'buildArch', 'buildType')
import os.path

facePluginEnv = extsEnv.Clone()
facePluginEnv.MergeFlags( opencvFlags )
ldaRoot = '../../../ThirdParty/Private/liblda-1.0'
facePluginEnv.Append(CPPPATH = [ldaRoot+'/include'])
faceSources = Glob('*.cpp')
faceSources.extend(Glob(ldaRoot + '/src/*.cpp'))
facePlugin = facePluginEnv.SharedLibrary( ExtSLName('FabricFACE'), faceSources ),
faceManifest = facePluginEnv.File('FabricFACE.fpm.json'),
faceKL = facePluginEnv.File('FabricFACE.kl'),
faceFiles = [faceManifest, facePlugin, faceKL]

Return( 'faceFiles' )
