#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv' )

# check if we have vicon installed
import os.path, platform

sdkPath = os.path.abspath(os.path.curdir + "/../../../../../../../../ThirdParty/vicon/datastreamsdk_"+platform.system())
if(platform.machine() == "x86_64"):
  sdkPath += "64"
else:
  sdkPath += "32"

if(os.path.exists(sdkPath)):
  viconPluginEnv = extsEnv.Clone()
  # vicon sdk
  viconPluginEnv.Append( CCFLAGS = '-I'+sdkPath )
  viconPluginEnv.Append( LINKFLAGS = '-L'+sdkPath+" -lViconDataStreamSDK_CPP" )
  viconPlugin = viconPluginEnv.SharedLibrary( 'FabricVICON', Glob('*.cpp') ),
  viconManifest = viconPluginEnv.File('FabricVICON.fpm.json'),
  viconFiles = [viconManifest, viconPlugin]
  Return( 'viconFiles' )
else:
  print("--------- Skipping VICON extension, no VICON SDK found.")
  Return( [] )
  