#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'fabricExtsDistDir', 'secureFlags', 'ExtSLName', 'buildOS' )

securePluginEnv = extsEnv.Clone()
securePluginEnv.MergeFlags( secureFlags )
blowfishRoot = '../../../ThirdParty/Private/blowfish'
securePluginEnv.Append(CPPPATH = [blowfishRoot])
sources = Glob('*.cpp')
sources.extend(Glob(blowfishRoot + '/*.cpp'))
securePlugin = securePluginEnv.SharedLibrary( ExtSLName('FabricSECURE'), sources ),
secureManifest = securePluginEnv.File('FabricSECURE.fpm.json'),
secureKL = securePluginEnv.File('FabricSECURE.kl'),
secureFiles = [secureManifest, securePlugin, secureKL]

Return( 'secureFiles' )
