#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'buildOS' )

SConscript( dirs=[buildOS,"Chrome","Firefox"] )

Alias( 'installer', ['nativeInstaller','chromeInstaller','firefoxInstaller'] )
