#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

import os.path
Import( 'coreEnv', 'buildOS', 'buildObject' )

klEnv = coreEnv.Clone()

extraObjects = [buildObject]

if buildOS == 'Windows':
    Import( 'getoptFlags' )
    klEnv.MergeFlags( getoptFlags )
    klEnv.Append( LINKFLAGS = [
        '/IMPLIB:${TARGET.dir}/kl_cmd.lib',
        '/STACK:4194304'
    ] )
    klEnv.Append( LIBS = [ 'advapi32' ] )
elif buildOS == 'Linux':
	klEnv.Append( LIBS = [ 'dl' ] )
  # [andrew 20120215] resolve circular linking dependencies in Core
	klEnv[ '_LIBFLAGS' ] = '-Wl,--start-group ' + klEnv['_LIBFLAGS'] + ' -Wl,--end-group'

klBin = klEnv.Program( 'kl', [ Glob('*.cpp'), extraObjects ] )
  
Alias( 'kl', klBin )
