#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

import os.path

Import( 'coreEnv', 'buildOS', 'buildType', 'buildObject', 'archDistDir', 'nodeFlags' )

cliEnv = coreEnv.Clone()
cliEnv.MergeFlags( nodeFlags )
if buildOS == 'Darwin':
  cliEnv.Append( LINKFLAGS = ["-undefined", "dynamic_lookup"] )

extraObjects = []

cliLibraryName = 'Fabric.node'
if buildOS == 'Windows':
    Import( 'getoptFlags' )
    cliEnv.MergeFlags( getoptFlags )
    cliEnv.Append( LINKFLAGS = [
        '/IMPLIB:${TARGET.dir}/fabric_cmd.lib',
        '/STACK:4194304'
    ] )
    cliEnv.Append( LIBS = [ 'User32', 'advapi32' ] )
    cliLibraryName = 'Fabric.dll'

cliLoadableModule = cliEnv.LoadableModule( cliLibraryName, [Glob('*.cpp'),buildObject,extraObjects] )

fabricNodeModuleDistDir = archDistDir.Dir('NodeModule')
fabricNodePackage = cliEnv.Command(
  fabricNodeModuleDistDir.File('package.json'),
  'package.json',
  [
    Copy( "$TARGET", "$SOURCE" )
  ])
Export('fabricNodePackage')
fabricNodeAddOn = cliEnv.Command(
  fabricNodeModuleDistDir.File( cliLibraryName ),
  cliLoadableModule,
  [
    Copy( "$TARGET", "$SOURCE" )
  ])
Export('fabricNodeAddOn')

nodeModuleReadMe = cliEnv.File('README.txt')
Export('nodeModuleReadMe')
nodeModuleLicense = cliEnv.File('LICENSE.txt')
Export('nodeModuleLicense')
