#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

import os.path

Import( 'coreEnv', 'buildOS', 'buildObject', 'v8Flags' )

cliEnv = coreEnv.Clone()
cliEnv.MergeFlags( v8Flags )
cliEnv.Append( LINKFLAGS = ["-undefined", "dynamic_lookup"] )

extraObjects = []

if buildOS == 'Windows':
    Import( 'getoptFlags' )
    cliEnv.MergeFlags( getoptFlags )
    cliEnv.Append( LINKFLAGS = [
        '/IMPLIB:${TARGET.dir}/fabric_cmd.lib',
        '/STACK:4194304'
    ] )

cliLoadableModule = cliEnv.LoadableModule( 'Fabric.node', [Glob('*.cpp'),buildObject,extraObjects] )
