#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

import os.path

Import( 'coreEnv', 'buildOS', 'buildObject' )
if buildOS != 'Windows':
  Import( 'libeditFlags' )

cliEnv = coreEnv.Clone()

extraObjects = []

if buildOS == 'Windows':
    Import( 'getoptFlags' )
    cliEnv.MergeFlags( getoptFlags )
    cliEnv.Append( LINKFLAGS = [
        '/IMPLIB:${TARGET.dir}/fabric_cmd.lib',
        '/STACK:4194304'
    ] )
else:
  cliEnv.MergeFlags( libeditFlags )

cliBin = cliEnv.Program( 'fabric', [Glob('*.cpp'),buildObject,extraObjects] )
Alias( 'cli', cliBin )
