#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'fabricExtsDistDir', 'ffmpegFlags' )

videoPluginEnv = extsEnv.Clone()
videoPluginEnv.MergeFlags( ffmpegFlags )
videoPlugin = videoPluginEnv.SharedLibrary( 'FabricVIDEO', Glob('*.cpp') ),
videoManifest = videoPluginEnv.File('FabricVIDEO.fpm.json'),
videoKL = videoPluginEnv.File('FabricVIDEO.kl'),
videoFiles = [videoManifest, videoPlugin, videoKL]

Return( 'videoFiles' )
