#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

import os

Import( 'env', 'installerName', 'archDistDir', 'npapiDistDir', 'generateDistZip' )

installEnv = env.Clone()
generateDistZip( installEnv )

installEnv.Append(
  DISTZIP_EXCLUDEEXTS = ['.pdb','.exp','.lib'],
  DISTZIP_ROOTDIR = npapiDistDir,
)

installerFile = archDistDir.File(installerName + '.zip')
installEnv.DistZip( installerFile, [npapiDistDir.File('npFabricPlugin.dll')] )

Alias( 'nativeInstaller', installerFile )
