#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import('coreEnv')

parseJSONEnv = coreEnv.Clone()
parseJSONBin = parseJSONEnv.Program('parseJSON', Glob('*.cpp'))
  
Alias('parseJSON', parseJSONBin)
