#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'fabricExtsDistDir', 'libpngFlags' )

pngPluginEnv = extsEnv.Clone()
pngPluginEnv.MergeFlags( libpngFlags )
pngPlugin = pngPluginEnv.SharedLibrary( 'FabricPNG', Glob('*.cpp') ),
pngManifest = pngPluginEnv.File('FabricPNG.fpm.json'),

installAction = Install( fabricExtsDistDir, [pngPlugin,pngManifest] )
extsEnv.CopyToAppdataIfWindows( installAction )

Alias( 'pngExt', [
  pngPlugin,
  pngManifest,
  installAction
] )
