#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'libpngFlags', 'ExtSLName' )

pngPluginEnv = extsEnv.Clone()
pngPluginEnv.MergeFlags( libpngFlags )
pngPlugin = pngPluginEnv.SharedLibrary( ExtSLName('FabricPNG'), Glob('*.cpp') ),
pngManifest = pngPluginEnv.File('FabricPNG.fpm.json'),
pngKL = pngPluginEnv.File('FabricPNG.kl'),
pngFiles = [pngManifest, pngPlugin, pngKL]

Return( 'pngFiles' )
