Import( 'coreEnv', 'buildOS', 'openclFlags' )

if buildOS == 'Darwin' or buildOS == 'Windows':
  coreEnv.MergeFlags( openclFlags )
  coreEnv.Prepend( LIBS = coreEnv.StaticLibrary( 'OCL', Glob('*.cpp') ) )
elif buildOS == 'Linux':
  import os
  if not os.environ.has_key('OPENCL_SDK'):
    print("--------- WARNING: For the OpenCL Extension to compile on Linux, you need to specify the path to the OpenCL SDK in the OPENCL_SDK environment variable.")
    print("--------- Skipping OCL extension, no OpenCL SDK found.")
  else:
    coreEnv.MergeFlags( openclFlags )
    coreEnv.Prepend( LIBS = coreEnv.StaticLibrary( 'OCL', Glob('*.cpp') ) )
