#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'buildOS' )

aliases = []

SConscript( dirs=['NPAPI'] )
aliases += ['npapi']

SConscript( dirs=['CLI'] )
aliases += ['cli']

Alias( 'clients', aliases )
