#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'openexrFlags' )

exrPluginEnv = extsEnv.Clone()
exrPluginEnv.MergeFlags( openexrFlags )
exrPlugin = exrPluginEnv.SharedLibrary( 'FabricEXR', Glob('*.cpp') ),
exrManifest = exrPluginEnv.File('FabricEXR.fpm.json'),
exrFiles = [exrManifest, exrPlugin]

Return( 'exrFiles' )
