#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'openexrFlags', 'fabricExtsDistDir' )

exrPluginEnv = extsEnv.Clone()
exrPluginEnv.MergeFlags( openexrFlags )
exrPlugin = exrPluginEnv.SharedLibrary( 'FabricEXR', Glob('*.cpp') ),
exrManifest = exrPluginEnv.File('FabricEXR.fpm.json'),

Alias( 'exrExt', [
  exrPlugin,
  exrManifest,
  Install( fabricExtsDistDir, [exrPlugin,exrManifest] )
] )
