#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

import os
Import( 'baseEnv', 'buildOS' )

aliases = [
  'exrExt',
  'hdrExt',
  'oglExt',
  'objExt',
  #'oclExt',
  'pngExt',
  'tgaExt',
  'viconExt',
]

dirs = [
  'EXR',
  'HDR',
  'OBJ',
  #'OCL',
  'OGL',
  'PNG',
  'TGA',
  'VICON',
]

if buildOS != 'Windows':
  dirs += ['VIDEO']
  aliases += ['videoExt']

SConscript( dirs=dirs )

Alias( 'builtinExts', aliases )
