#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

import os
Import( 'baseEnv', 'buildOS' )

dirs = [
  'ALEMBIC',
  'BULLET',
  'CIMG',
  'EXR',
  'HDR',
  'KINECT',
  'LIDAR',
  'Math',
  'OBJ',
  #'OCL',
  'OGL',
  'PNG',
  'SECURE',
  'TEEM',
  'TGA',
  'TSYS',
  'VICON',
  'VIDEO'
]

builtinExtFiles = SConscript( dirs=dirs )

Return( 'builtinExtFiles' )
