#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'fabricExtsDistDir', 'ExtSLName' )

bulletPluginEnv = extsEnv.Clone()
bulletRoot = '../../../ThirdParty/Private/bullet-2.78/src'
bulletPluginEnv.Append(CPPPATH = [bulletRoot])
bulletSources = Glob('*.cpp')
bulletSources.extend(Glob(bulletRoot + '/BulletCollision/CollisionShapes/*.cpp'))
bulletSources.extend(Glob(bulletRoot + '/BulletCollision/CollisionDispatch/*.cpp'))
bulletSources.extend(Glob(bulletRoot + '/BulletCollision/BroadphaseCollision/*.cpp'))
bulletSources.extend(Glob(bulletRoot + '/BulletCollision/NarrowPhaseCollision/*.cpp'))
bulletSources.extend(Glob(bulletRoot + '/BulletCollision/Gimpact/*.cpp'))
bulletSources.extend(Glob(bulletRoot + '/BulletSoftBody/*.cpp'))
bulletSources.extend(Glob(bulletRoot + '/LinearMath/*.cpp'))
bulletSources.extend(Glob(bulletRoot + '/BulletDynamics/Dynamics/*.cpp'))
bulletSources.extend(Glob(bulletRoot + '/BulletDynamics/Character/*.cpp'))
bulletSources.extend(Glob(bulletRoot + '/BulletDynamics/Vehicle/*.cpp'))
bulletSources.extend(Glob(bulletRoot + '/BulletDynamics/ConstraintSolver/*.cpp'))
bulletPlugin = bulletPluginEnv.SharedLibrary( ExtSLName('FabricBULLET'), bulletSources ),
bulletManifest = bulletPluginEnv.File('FabricBULLET.fpm.json'),
bulletKL = bulletPluginEnv.File('FabricBULLET.kl'),
bulletFiles = [bulletManifest, bulletPlugin, bulletKL]

Return( 'bulletFiles' )
