#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

import os
Import( 'coreEnv', 'npapiSources', 'npapiDistDir', 'buildArch', 'npapiFlags', 'gtkglFlags' )

npapiEnv = coreEnv.Clone()
npapiEnv.MergeFlags( npapiFlags )

npapiEnv.Append( CPPDEFINES = 'GLEW_STATIC' )
npapiEnv.MergeFlags( gtkglFlags )
if buildArch == 'x86_64':
  npapiEnv.Append( LIBS = [File('/usr/lib64/libGLEW.a')] )
else:
  npapiEnv.Append( LIBS = [File('/usr/lib/libGLEW.a')] )
npapiEnv.Append( LIBS = ['GL'] )
ccflags = []
for flag in npapiEnv['CCFLAGS']:
  if(flag.lower() == '-include'):
    continue
  if(flag.lower().endswith(".h")):
    ccflags.append("-include")
  ccflags.append(flag)
npapiEnv['CCFLAGS'] = ccflags
  
npapiSources.append( Glob('*.cpp') )
npapiPluginName = 'FabricPlugin'
npapiPlugin = npapiEnv.LoadableModule( 'FabricPlugin', npapiSources )

Alias( 'npapi', Install( npapiDistDir, npapiPlugin ) )
