#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'fabricExtsDistDir' )

hdrPluginEnv = extsEnv.Clone()
hdrPlugin = hdrPluginEnv.SharedLibrary( 'FabricHDR', Glob('*.cpp') ),
hdrManifest = hdrPluginEnv.File('FabricHDR.fpm.json'),

installAction = Install( fabricExtsDistDir, [hdrPlugin,hdrManifest] )
extsEnv.CopyToAppdataIfWindows( installAction )

Alias( 'hdrExt', [
  hdrPlugin,
  hdrManifest,
  installAction
] )
