#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'ExtSLName' )

jpgPluginEnv = extsEnv.Clone()
jpgPlugin = jpgPluginEnv.SharedLibrary( ExtSLName('FabricJPG'), Glob('*.cpp') ),
jpgManifest = jpgPluginEnv.File('FabricJPG.fpm.json'),
jpgKL = jpgPluginEnv.File('FabricJPG.kl'),
jpgFiles = [jpgManifest, jpgPlugin, jpgKL]

Return( 'jpgFiles' )
