#!/bin/sh

echo "# This file is automatically generated -- do not edit!!"
echo
echo '.PHONY:\'
for f in "$@"; do echo "  $f.phony\\"; done
echo
echo 'test:\'
for f in "$@"; do echo "  $f.phony\\"; done
echo
for f in "$@"; do
  echo "$f.phony:"
  echo "	@./run.sh $f"
  echo
done
