Import('coreEnv')

klEnv = coreEnv.Clone();
klEnv.Append( YACCFLAGS = ['-d'] )
# klParser = klEnv.CXXFile( 'Parser.cpp', 'Parser.yy' )

coreEnv.Prepend( LIBS = coreEnv.StaticLibrary( 'KL', Glob('*.cpp') ) )
