#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

import os
Import( 'env', 'installerName', 'archDistDir', 'npapiDistDir', 'fabricExtsDistDir' )

installScript = env.Template( archDistDir.File( "install.sh" ), "install.sh.template" )

tarballStagingDir = archDistDir.Dir( installerName )
tarballBuilder = Builder(
  action = "\
rm -rf '"+str(tarballStagingDir)+"' ;\n\
mkdir '"+str(tarballStagingDir)+"' ;\n\
chmod 755 $SOURCE ;\n\
cp $SOURCE '"+str(tarballStagingDir)+"/' ;\n\
cp -r '"+str(npapiDistDir)+"' '"+str(tarballStagingDir)+"/' ;\n\
cp -r '"+str(fabricExtsDistDir)+"' '"+str(tarballStagingDir)+"/' ;\n\
tar -jc -C '"+str(archDistDir)+"' -f '"+installerName + '.tar.bz2'+"' '"+installerName+"'\n\
"
)
env['BUILDERS']['Tarball'] = tarballBuilder

tarballFile = archDistDir.File( installerName + '.tar.bz2' )

tarball = env.Tarball(
  target=tarballFile,
  source=installScript
)

Alias( 'installer', tarball )
