#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'fabricExtsDistDir', 'ExtSLName', 'buildOS' )

timeSampleExtEnv = extsEnv.Clone()
timeSampleExt = timeSampleExtEnv.SharedLibrary( ExtSLName('TimeSample'), Glob('*.cpp') )
if buildOS == 'Windows':
  timeSampleExt = timeSampleExt[0]
timeSampleManifest = timeSampleExtEnv.File( 'TimeSample.fpm.json' ),
timeSampleKL = timeSampleExtEnv.File( 'TimeSample.kl' ),
timeSampleExtFiles = [timeSampleManifest, timeSampleExt, timeSampleKL]

Return( 'timeSampleExtFiles' )
